#!/usr/bin/env bash

DISTR=$(lsb_release -s -c)
LAST_DISTR=xenial

mkdir -p ./sources.list.d/

echo "
deb https://deb.nodesource.com/node_6.x $LAST_DISTR main
deb-src https://deb.nodesource.com/node_6.x $LAST_DISTR main
deb http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu $DISTR main
deb-src http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu $DISTR main
deb http://ppa.launchpad.net/webupd8team/atom/ubuntu $DISTR main 
deb-src http://ppa.launchpad.net/webupd8team/atom/ubuntu $DISTR main
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
" > ./sources.list.d/local.list
